"""GET /recommendation/{id} — retrieve a stored ranked recommendation.

The POST /optimize endpoint generates and stores a Recommendation.
This endpoint retrieves it by ID.

Owner: R5
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException

from app.models.recommendation import Recommendation, OptimizeRequest
from app.services import recommendation_store

router = APIRouter(prefix="/recommendation", tags=["recommendation"])


@router.get(
    "/{recommendation_id}",
    response_model=Recommendation,
    summary="[M3] Retrieve a stored ranked recommendation",
)
async def get_recommendation(recommendation_id: str) -> Recommendation:
    """Retrieve a recommendation previously generated by POST /optimize.

    Returns the full ``Recommendation`` object including:
    - ``ranked``: list of ranked strategies with consequence vectors
    - ``explanation``: plain-language summary
    - ``weights_used``: the objective weights applied during optimisation
    """
    rec = recommendation_store.get(recommendation_id)
    if rec is None:
        raise HTTPException(
            status_code=404,
            detail=f"Recommendation '{recommendation_id}' not found. "
                   "Generate one via POST /optimize first.",
        )
    return rec


@router.get(
    "",
    summary="List all stored recommendations",
)
async def list_recommendations() -> dict:
    """List all recommendations stored in memory (newest first)."""
    recs = recommendation_store.list_all()
    return {
        "count": len(recs),
        "recommendations": [
            {
                "id": r.id,
                "budget": r.budget,
                "top_strategy": r.ranked[0].scenario_id if r.ranked else None,
                "top_score": r.ranked[0].score if r.ranked else None,
                "n_ranked": len(r.ranked),
            }
            for r in recs
        ],
    }
